import React from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Layout = ({ children, title }: any) => {
  return (
    <div>
      <Head>
        <title>Pokémon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball.png" />
      </Head>

      <header className="flex justify-center py-6 space-x-4 bg-slate-900">
        <Link href="/">
          <a>
            <Image alt="pokeball" src="/pokeball.png" height={50} width={50} />
            <span className="text-6xl font-semibold text-center text-white font-satoshi">Pokémon</span>
          </a>
        </Link>
      </header>

      <main className="container w-full min-h-screen p-2 mx-auto">{children}</main>

      <div className="p-4 mt-20 bg-gray-500">
        <footer className="flex items-center justify-center space-x-2 tracking-wider">
          {/* <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐝</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐜</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐌</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐙</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦦</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐓</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐡</span> */}
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦩</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦆</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦅</span>
          <div className="font-mono text-xl font-semibold">MADE BY &copy; MKM</div>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦈</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐟</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐦</span>
          {/* <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐤</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦎</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦉</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐠</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🦢</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🕊️</span>
          <span className="font-mono text-2xl font-semibold duration-500 hover:scale-125">🐧</span> */}
        </footer>
      </div>
    </div>
  );
};

export default Layout;
